# .github/workflows/canary-release.yml
name: ✨ Canary release

on:
  push:
    branches:
      - feature/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changesets:
    runs-on: ubuntu-latest
    name: Check for changes in .changesets
    outputs:
      any_changed: ${{ steps.check_changesets.outputs.any_changed }}
      any_deleted: ${{ steps.check_changesets.outputs.any_deleted }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check .changesets directory for changes
        id: check_changesets
        uses: tj-actions/changed-files@v44
        with:
          files: |
            .changeset/**

  changesets-release:
    name: Release packages with changesets
    runs-on: ubuntu-latest
    needs: [check-changesets]
    if: ${{ needs.check-changesets.outputs.any_changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Tests
        run: pnpm run test

      - name: Setup Git User
        shell: bash
        # This sets the git user to the author of the last commit
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        id: npm-publish
        run: |
          pnpm run version:canary
          pnpm run release:canary
          find .changeset -type f -name "*.md" ! -name "README.md" -exec rm -f {} +
          git add .changeset/ -u
          git commit -m "chore: cleanup canary changesets"
          git push origin $(git branch --show-current)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  check-chromatic:
    runs-on: ubuntu-latest
    name: Check for changes in apps/storybook
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            apps/storybook/**

  chromatic-publish:
    name: Run visual tests
    needs: [check-chromatic]
    if: ${{ needs.check-chromatic.outputs.any_changed == 'true' }}
    uses: ./.github/workflows/chromatic.yml
    secrets: inherit
